import type { Playbook } from '../types';

export function playbookToMarkdown(playbook: Playbook): string {
  const lines: string[] = [];

  lines.push(`# ${playbook.title}`);
  lines.push('');
  lines.push(playbook.intro);
  lines.push('');
  lines.push('## Interview steps');
  lines.push('');

  const categoryLabels: Record<string, string> = {
    'warm-up': 'Warm-up',
    'exploration': 'Exploration',
    'validation': 'Validation',
    'close': 'Close',
  };

  for (const step of playbook.steps) {
    lines.push(`### ${step.order}. ${step.question}`);
    lines.push('');
    lines.push(`**Category:** ${categoryLabels[step.category] ?? step.category}`);
    lines.push('');
    lines.push(`**Why:** ${step.rationale}`);
    lines.push('');
    lines.push(`**Expected insight:** ${step.expectedInsight}`);
    lines.push('');
  }

  if (playbook.antiPatterns.length > 0) {
    lines.push('## Questions to avoid');
    lines.push('');
    for (const ap of playbook.antiPatterns) {
      lines.push(`- ${ap}`);
    }
    lines.push('');
  }

  lines.push(`---`);
  lines.push(`*Generated by PersonaLab · ${new Date(playbook.generatedAt).toLocaleDateString()}*`);

  return lines.join('\n');
}

export function downloadMarkdown(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
